{% set version = "2.4.0" %}
{% set hash = "2a7f0b125a59a7cc543f62e5f9dea50b44b3459b3f679db7e3dbe0f8616f90bc" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - babel
    - json5
    - jsonschema >=3.0.1
    - jinja2 >=2.10
    - packaging
    - requests
    - jupyter_server >=1.1.0,<2.0.0

test:
  requires:
    - pip
  imports:
    - jupyterlab_server
  commands:
    - python -m pip check

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
