{% set version = "2.16.4" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 831e3fe953938ceeb86d64725a1c7497dba884b88e44c7a0e9ab9eb48eccfdb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - hatchling >=0.25
    - pip
    - python >=3.7

  run:
    - babel
    - importlib-metadata >=4.8.3
    - jinja2 >=3.0.3
    - json5
    - jsonschema >=3.0.1
    - jupyter_server >=1.8,<3
    - packaging
    - python >=3.7
    - requests

test:
  source_files:
    - tests
    - jupyterlab_server/test_data
  requires:
    - ipykernel
    - openapi-core >=0.14.2,<0.15.0
    - openapi-spec-validator >=0.4.0,<0.5
    - pip
    - pytest >=7.0
    - pytest-console-scripts
    - pytest-cov
    - pytest-tornasync
    - requests-mock
    - ruamel.yaml
    - strict-rfc3339
    - wheel
  imports:
    - jupyterlab_server
  commands:
    - pip check
    - cd tests && pytest -vv --cov jupyterlab_server --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 68
  downstreams:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
