{% set version = "2.11.2" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 5d8dc70f6803dc48efb69fb43e3cd2f8c6aad4ba011670318e5efd26c7487bb9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - jupyter_server
    - jupyter-packaging >=0.9
    - pip
    - python >=3.7

  run:
    - babel
    - entrypoints >=0.2.2
    - jinja2 >=3.0.3
    - json5
    - jsonschema >=3.0.1
    - jupyter_server >=1.8,<2
    - packaging
    - python >=3.7
    - requests

test:
  source_files:
    - tests
    - jupyterlab_server/rest-api.yml
    - jupyterlab_server/test_data
  requires:
    - ipykernel
    - openapi-core >=0.14.2
    - openapi-spec-validator <0.5
    - pip
    - pytest >=5.3.2
    - pytest-console-scripts
    - pytest-cov
    - pytest-tornasync
    - ruamel.yaml
    - strict-rfc3339
    - wheel
  imports:
    - jupyterlab_server
  commands:
    - pip check
    - cd tests && pytest -vv --cov jupyterlab_server --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 68
  downstreams:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
