{% set version = "2.10.0" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 6d980bf72bd6a1d910a623d3f3c375601ace7812b90b78cf9bb86fd55c6920f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - jupyter-packaging >=0.9,<2
    - jupyter_server
    - pip

  run:
    - python >=3.6
    - babel
    - entrypoints >=0.2.2
    - jinja2 >=2.10
    - json5
    - jsonschema >=3.0.1
    - jupyter_server >=1.4,<2
    - packaging
    - requests

test:
  requires:
    - ipykernel
    - openapi-core >=0.14,<0.15
    - pip
    - pytest >=5.3.2
    - pytest-console-scripts
    - pytest-cov
    - pytest-tornasync
    - ruamel.yaml
    - strict-rfc3339
    - wheel
  imports:
    - jupyterlab_server
  commands:
    - pip check
    - pytest -vv --pyargs jupyterlab_server --cov jupyterlab_server --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 65
  downstreams:
    - jupyterlab

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
