travis:
  secure:
    BINSTAR_TOKEN: pAwcnBMMZ3FW+f5nsFbXFFkoyCDirtt2xiyPXMV6MqzYjVYMC/bSzjDeSyPAIs6k6evUt4AsVI+xYOi2B1RJsgg0oKqpQ/vG9mlJvxekTXgFSST5oPuXGVSioeCpbSAyeklUQ/DyNSGyTRkXGC183c2g5f5CCqsqi+yO5tFZAas15bA+p4YsTbA+p7YM6dZuKJIRD5CrQ6t26ZTy+DXoHAl3BVNLR/wJ7y1H4hgkZdex4jrULyj2zLer/Xzz6KUIVssRZRymFv9Ora4hlob584bYl2M780UYYE750LWMeL4jcg2tbfTJ6z5zMbInbocrXa5vFPlCJNajTeCNIIahW21xtA/7RZ2U/oI9+Kz8FVo4r7G+99lFTn93v14LDbe+g3t8htDczmGDD2qUX62FOSIF1ASIieWNsKRFF/rn5S87vN94mTDbwh8dNToI58fX2T/NOVkSRRBB6sV/JHNKIykz1kuSH7L1la4Q239F9qlGd6PsyXt4/LHVO7xLmsU7tN45OsiYmCgB57z6G25W2lPzAWK6cKni7S9ARhBg6Tt4ZzIovH0hYOhSwdyzMxMBehqdsdbi5ENBx4gFvKNypDz4pVu1Mf0JPBJpihb35o4Lco8IwJu+iyJGF8eqVnzqCxgJc6yNU4XhEOmhprpB/pxstqX7woC75oG4csDHDYY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
